services:
  nginx:
    build:
      context: ./docker/dev/nginx
      dockerfile: nginx.dockerfile
    ports:
      - "8080:80"
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./docker/dev/php
      dockerfile: php-fpm.dockerfile
    volumes:
      - ./api:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"

  php-cli:
    build:
      context: ./docker/dev/php
      dockerfile: php-cli.dockerfile
    volumes:
      - ./api:/app
      - composer:/root/.composer/cache
    extra_hosts:
      - "host.docker.internal:host-gateway"

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  composer:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
