version: "3"

services:
  nginx:
    build:
      context: ./docker/nginx
    ports:
      - "8080:80"
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - ./api:/app

  php-cli:
    build:
      context: ./docker/php-cli
    volumes:
      - ./api:/app
      - composer:/root/.composer/cache

volumes:
  composer: